config/routes.rb
Rails.application.routes.draw do
  
    root 'static_pages#home'
    resources :users

    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'

    get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'

	get '/secret', to: 'static_pages#secret', as: 'secret'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token

	before_save {self.email = email.downcase}
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
	 				  format: {with: VALID_EMAIL_REGEX},
	 				  uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 6}

	class << self

		def digest(string)
		    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		                                                  BCrypt::Engine.cost
		    BCrypt::Password.create(string, cost: cost)
	    end

	    def new_token
	    	SecureRandom.urlsafe_base64
	    end
	end

	def remember
	    self.remember_token = User.new_token
	    update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated?(remember_token)
	    return false if remember_digest.nil?
	    BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
	   update_attribute(:remember_digest, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
  	else
  		flash.now[:danger] = "hey non va t'inscrire avant de venir ici!!"	
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

    def secret
  		if !logged_in?
	    	flash[:danger] = "AhAh petit malin! Allez va vite te connecter 😻"
	    	redirect_to '/login'
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)


		if @user.save
			log_in @user
			remember @user
			flash.now[:success] = "Sois le bienvenue à bord, Moussaillon!"
			redirect_to @user
		else
			render 'new'
		end
	end

	def edit
		if logged_in? && (current_user.id == params[:id].to_i)
			@user = User.find(params[:id])
		else
			flash.now[:danger] = "AhAh petit malin je t'ai coincé! Va te connecter et plus vite que ça moussaillon!"
			redirect_to '/'
		end
	end

	def show
		set_user
	end

	def update
		if @user.update(user_params)
			flash.now[:success] = "Tes modifications ont été prises en compte, Moussaillon!"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		# @user.destroy
		# flash.now[:success] = "Oh non on vient de perdre un moussaillon!"
		# redirect_to users_url

	end

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		#il est connecté de façon temporaire
		session[:user_id] = user.id
	end

	def current_user
		if (user_id = session[:user_id])
	    	@current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.signed[:user_id])
	    	user = User.find_by(id: user_id)
	     	if user && user.authenticated?(cookies[:remember_token])
		       log_in user
		       @current_user = user
	     	end
	     end
	end

	def forget(user)
		puts "--------------forget"
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def remember(user)
		puts "---------------remember"
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
		
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Laetitia's app", root_path, id: "logo" %>
      <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Accueil", root_path %></li>
            
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Compte <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>

            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>

          </ul>
      </nav>
    </div>   <!-- fin container -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Hey, Moussaillon !</h1>
          <p>J'ai entendue dire que tu étais intéressé par le secret de l'univers??? </p>

          <p><a class="btn btn-primary btn-lg" href="<%= secret_path %>" role="button">Dirige-toi ici vaillant moussaillon »</a></p>
        </div>
     </div>



</main>

app/views/static_pages/secret.html.erb
<h1>Youhou tu es le meilleur! Même si ce n'est pas un secret du coup ;-)</h1>

app/views/users/create.html.erb
<h1>Accès non authorisé</h1>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, 'Sign up') %>

<div class="jumbotron">
    <h1>Modifier son profil</h1>

    <div class="container">
		<div class="row">
		  <div class="col-md-6 col-md-offset-3">
		    <%= form_for(@user, url: user_path,method: :patch) do |f| %>

		     <%= render 'shared/error_messages' %>

		     <%= f.label :name %>
		     <%= f.text_field :name, class: 'form-control' %>

		     <%= f.submit "Mettre à jour", class: "btn btn-primary compte" %>
		   <% end %>
		  </div>
		</div>

	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>S'inscrire</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
     <%= render 'shared/error_messages' %>

     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>

     <%= f.label :email %>
     <%= f.email_field :email, class: 'form-control' %>

     <%= f.label :password %>
     <%= f.password_field :password, class: 'form-control' %>

     <%= f.label :password_confirmation, "Confirmation" %>
     <%= f.password_field :password_confirmation, class: 'form-control' %>

     <%= f.submit "Créer mon compte", class: "btn btn-primary compte" %>
   <% end %>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>